title: "Rhiven dashboard"
subtitle: "Le meilleur serveur"
logo: "assets/logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
footer: '<p>We love Rhiven</p>' # set false if you want to hide it.
